robot_controller:
  ros__parameters:
    linear_speed: 0.2
    angular_speed: 0.5
    turn_direction: left   # left or right

robot_mover:
  ros__parameters:
    linear_speed: 0.2
    angular_speed: 0.5
